INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA1', 100);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA2', 210);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA3', 260);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA4', 80);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA5', 90);

INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA6', 4);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA7', 2);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA8', 9);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA9', 8);
INSERT INTO ITEM (ITEM_ID, PRICE) VALUES ('MLA10', 7);