INSERT INTO ITEM (ITEM_id, price) VALUES ('MLA1', 100);
INSERT INTO ITEM (ITEM_id, price) VALUES ('MLA2', 210);
INSERT INTO ITEM (ITEM_id, price) VALUES ('MLA3', 260);
INSERT INTO ITEM (ITEM_id, price) VALUES ('MLA4', 80);
INSERT INTO ITEM (ITEM_id, price) VALUES ('MLA5', 90);